#!/usr/bin/env bash

function print_selected {
    echo
    echo "Selected:"
    php -r 'echo PHP_VERSION . "\n";'
}

function print_available {
    echo
    echo "Available:"
    update-alternatives --list php | sed 's/\/usr\/bin\/php//'
}

QUERY="$1"
if [ "$QUERY" = "" ] || [ "$QUERY" = "--help" ]; then
    print_selected

    print_available

    echo
    echo "To select another version, specify it like this:"
    echo "  phv 8.2"

    echo

    exit 0
fi

TARGET=$(update-alternatives --list php | grep "$QUERY") && FOUND=1 || FOUND=0
if [ "$FOUND" == "0" ]; then
    echo
    echo "Error! No target found with '$QUERY'."

    print_available

    echo

    exit 1
fi

TARGETS_COUNT=$(echo "$TARGET" | wc -l)
if [ "$TARGETS_COUNT" != "1" ]; then
    echo
    echo "Error! More then one target found with '$QUERY'."

    echo
    echo "Found targets:"
    echo "$TARGET"

    print_available

    echo

    exit 1
fi

echo
for group in php phar phar.phar; do
    GROUP_TARGET=$(update-alternatives --list "$group" | grep "$QUERY")
    sudo update-alternatives --set "$group" "$GROUP_TARGET"
done

print_selected
echo
